### ISSUE TITLE
Create a metric to compare the party plots with the original political compass

### ISSUE THREAD

**Issue by deepthi-pathare** [13hannes11/UU_NCML_Project#24]

**Comment by 13hannes11** [comment]
# Germany
## 2017
As CDU and CSU are separate here I computed an average.

| Party   |  x   |  y    |
|---------|------|-------|
| CSU     |  4   |  7    |
| CDU     |  8   |  5.5  |
| CDU/CSU |  6   |  6.25 |
| Green   |  2   |  4.5  |
| AfD     |  5.5 |  8    |
| SPD     |  3   |  2.5  |
| FDP     |  7   |  3    |
| Left    | -2.5 | -1.5  |


## 2013

| Party   |  x   |  y   |
|---------|------|------|
| CDU     |  7   |  6.5 |
| SPD     |  1   |  2   |
| AFD     |  6   |  7   |
| FDP     |  8   | -1.5 |
| Piraten |  0   | -4   |
| Green   | -3.5 | -4   |
| Left    | -7   | -6.5 |

## 2015
This one is the roughest because no grid lines were provided, I just the grid from GIMP.


| Party   |  x   |  y   |
|---------|------|------|
| CDU     |  9.5   |  8 |
| SPD     |  3   |  3.5   |
| FDP     |  12   | 3 |
| Green   | -1.5 | -1.5   |
| Left    | -6 | -2 |

**Comment by 13hannes11** [comment]
# United Kingdom
## 2019

| Party       |  x   |  y    |
|-------------|------|-------|
| UKIP        |  8.5 |  9    |
| Brexit      |  8.5 |  8    |
| DUP         |  7   |  8    |
| Conserv     |  9.5 |  7    |
| LibDem      |  4   |  2.5  |
| SNP         | -2   |  1.5  |
| SDLP        | -0.5 | -0.5  |
| Plaid Cymru | -0.5 | -0.5  |
| Labour      | -4.5 | -1.5  |
| Green       | -3   | -5    |


## 2017

| Party       |  x   |  y    |
|-------------|------|-------|
| UKIP        |  7.5 |  8.5  |
| DUP         |  5.5 |  8    |
| Conserv     |  8.5 |  7.5  |
| LibDem      |  3.5 |  1    |
| SSP         | -5.5 |  2.5  |
| SNP         | -1.5 |  1.5  |
| SDLP        | -1.5 | -0.5  |
| Plaid Cymru | -0.5 | -1.5  |
| Labour      | -4   | -2    |
| Green       | -2.5 | -4.5  |


## 2015

| Party       |  x   |  y    |
|-------------|------|-------|
| BNP         |  2   |  9.5  |
| UKIP        |  8   |  8    |
| DUP         |  5   |  8.5  |
| Conserv     |  9   |  6.5  |
| Respect     |  5   | -7    |
| Labour      |  4   |  5.5  |
| LibDem      |  5   |  2.5  |
| SSP         | -7.5 |  2    |
| SNP         | -0.5 |  1.5  |
| SDLP        | -2.5 | -0.5  |
| Plaid Cymru | -2.5 | -1    |
| Sinn Féin   | -2   |  4    |
| Green       | -4   | -5    |
